#!/usr/bin/env bash
# Configure UFW to block all incoming traffic except SSH (22), HTTP (80), and HTTPS (443)

sudo apt update
sudo apt install ufw -y
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable

