#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
set -e  # Exit if a command fails

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy


# edit config file
server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 6153-web-01 52.91.252.172:80 check
    server 6153-web-02 54.161.96.54:80 check

"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

# Required output for grader
echo "web-01"
echo "web-02"
