#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School :)" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://www.github.com/shakilla1;\n    }' /etc/nginx/sites-enabled/default

# codes to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
